### ISSUE TITLE
Add MAINTAINERS.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-yolo-cpu#3]
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

**Comment by aukokyong** [comment]
Hi @joewxboy, Please assign this to me.

**Comment by deepesh85b** [comment]
Hi @joewxboy 
Please assign this to 
I'm looking forward to make a first PR

**Comment by joewxboy** [comment]
Sorry @deepesh85b it looks like @aukokyong beat you to it.  There should be others.
